### ISSUE TITLE
Cookbook does not compile with Chef client 12.9.41 / 12.10.24

### ISSUE THREAD

**Issue by colourmeamused** [University-of-Illinois-at-Chicago/firewalldconfig-cookbook#2]
I think the Ruby version change is responsible but I can't find the deprecation that's causing it.
Chef 12.8 works fine.
`/opt/chef/embedded/bin/ruby -v`
Under Chef 12.8.1
`ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]`
Under Chef 12.9.41
`ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]`

`$ chef-client -z -o recipe[firewalldconfig]`

> [2016-06-01T06:26:40+00:00] WARN: No config file found or specified on command line, using command line options.
> Starting Chef Client, version 12.9.41
> [2016-06-01T06:26:45+00:00] WARN: Run List override has been provided.
> [2016-06-01T06:26:45+00:00] WARN: Original Run List: []
> [2016-06-01T06:26:45+00:00] WARN: Overridden Run List: [recipe[firewalldconfig]]
> resolving cookbooks for run list: ["firewalldconfig"]
> Synchronizing Cookbooks:
> - firewalldconfig (0.7.0)
> - xml (2.0.0)
> - build-essential (3.2.0)
> - chef-sugar (3.3.0)
> - seven_zip (2.0.0)
> - windows (1.39.2)
> - chef_handler (1.3.0)
>   Installing Cookbook Gems:
>   Compiling Cookbooks...
> # 
> # Recipe Compile Error in /root/.chef/local-mode-cache/cache/cookbooks/firewalldconfig/resources/zone.rb
> ## SyntaxError
> 
> /root/.chef/local-mode-cache/cache/cookbooks/firewalldconfig/resources/zone.rb:51: syntax error, unexpected keyword_do_block, expecting '}'
>     lambda do |rules|
>              ^
> /root/.chef/local-mode-cache/cache/cookbooks/firewalldconfig/resources/zone.rb:53: syntax error, unexpected keyword_end, expecting end-of-input
>     end,
>        ^
> ## Platform:
> 
> x86_64-linux

**Comment by jkupferer** [comment]
Thank you for this. It should be fixed now.
